name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up image tag with date
      id: vars
      run: echo "IMAGE_TAG=frontend-$(date +%F)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t elad1122/toran:${{ env.IMAGE_TAG }} ./toran-front/

    - name: Push Docker image
      run: |
        docker push elad1122/toran:${{ env.IMAGE_TAG }}

